################################################################################
# Â© Copyright IBM Corporation 2021
################################################################################
# This file creates an alias for file 'requirements-zos-ims.txt' which is used
# to manage any python dependencies needed by this Collection to run effectively
# on an Ansible controller.
################################################################################
dependencies:
  python: requirements-zos-ims.txt
version: 1
